<Project Sdk="Godot.NET.Sdk/4.5.1">
  <PropertyGroup>
    <!-- 如果你安装了10.0并遇到问题，改下这里 -->
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>true</ImplicitUsings>
    <LangVersion>13.0</LangVersion>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <!-- 改成你的杀戮尖塔2目录 -->
    <Sts2AppId>2868840</Sts2AppId>
    <Sts2InstallDirName>Slay the Spire 2</Sts2InstallDirName>
    <SteamLibraryPath Condition="'$(SteamLibraryPath)' == '' and '$(HOME)' != ''">$(HOME)/.local/share/Steam/steamapps</SteamLibraryPath>
    <Sts2Path Condition="'$(Sts2Path)' == '' and '$(SteamLibraryPath)' != '' and Exists('$(SteamLibraryPath)/common/$(Sts2InstallDirName)')">$(SteamLibraryPath)/common/$(Sts2InstallDirName)</Sts2Path>
    <Sts2Dir Condition="'$(Sts2Dir)' == ''">$(Sts2Path)</Sts2Dir>
    <Sts2DataDir Condition="'$(Sts2DataDir)' == '' and '$(Sts2Dir)' != ''">$(Sts2Dir)/data_sts2_windows_x86_64</Sts2DataDir>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="sts2">
      <HintPath>$(Sts2DataDir)/sts2.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="0Harmony">
      <HintPath>$(Sts2DataDir)/0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <!-- 自动复制dll和json -->
  <Target Name="Copy Mod" AfterTargets="PostBuildEvent" Condition="'$(SkipModCopy)' != 'true'">
    <Message Text="Copying mod to Slay the Spire 2 mods folder..." Importance="high" />
    <MakeDir Directories="$(Sts2Dir)/mods/" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(Sts2Dir)/mods/$(MSBuildProjectName)/" />
    <Copy SourceFiles="$(MSBuildProjectName).json" DestinationFolder="$(Sts2Dir)/mods/$(MSBuildProjectName)/" />
  </Target>
</Project>
